---
- name: Test
  hosts: new
  remote_user: sysop
  become: yes
  tasks:
    - name: Transfer the script
      copy: src=a.sh dest=/home/sysop mode=0777
    - name: Execute the script 1
      shell:
        cmd: 'tar xvfz zabbix-5.0.0alpha4.tar.gz'
        cmd: 'cd zabbix-5.0.0alpha4 ; ./configure  --enable-agent ; make install ; mkdir /etc/zabbix ; ln -s /usr/local/etc/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf ; sleep 1 ; /usr/local/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf'
#        cmd: 'cd zabbix-4.4.6 ; addgroup --system --quiet zabbix ; adduser --quiet --system --disabled-login --ingroup zabbix --home /var/lib/zabbix --no-create-home zabbix ; mkdir -m u=rwx,g=rwx,o= -p /var/lib/zabbix ; chown zabbix:zabbix /var/lib/zabbix ; apt-get install -y libpcre3-dev'




