---
- name: Transfer and execute a script.
  hosts: server
  user: test_user
  Sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=test.sh dest=/home/test_user mode=0777

     - name: Execute the script
       local_action: command Sudo sh /home/test_user/test.sh
