---
- name: Test
  hosts: mining
  remote_user: sysop
  become: yes
  become_user: root
  tasks:
    - name: line del 
      lineinfile: 
        path: '/etc/zabbix/zabbix_agentd.conf'
        regexp: '^UserParameter=storage.'
        line: ''
