---
- name: Test
  hosts: new
  remote_user: sysop
  become: yes
  tasks:
    - name: Execute the script 1
      shell:
        cmd: wget https://jaist.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Development/5.0.0alpha2/zabbix-5.0.0alpha2.tar.gz
